apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    name: myapp
    namespace: _{_NAMESPACE_}_

  spec:
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: myapp
    type: NodePort
