# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job-0:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Job-0
        run: echo "Job-0 is running"

  Job-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [Job-0] # Job-1 will run after Job-0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone project
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  Job-2:
    runs-on: ubuntu-latest
    needs: [Job-0] # Job-2 will run after Job-1
    steps:
      - name: Initialize Job-2
        run: echo "Job-2 is running"

  Job-3:
    runs-on: ubuntu-latest
    needs: [Job-1, Job-2] # Job-3 will run after Job-2
    steps:
      - name: Initialize Job-3
        run: echo "Job-3 is running"

  Job-4:
    runs-on: ubuntu-latest
    needs: [Job-3] # Job-4 will run after Job-3
    steps:
      - name: Initialize Job-4
        run: echo "Job-4 is running"
