name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    paths-ignore:
      - "README.md"
    branches: ["main"]

  workflow_dispatch:
    inputs:
      image_name:
        description: "Docker image name"
        required: false
        default: ""
      image_tag:
        description: "Tag for the Docker image"
        required: false
        default: "latest"
      deploy_env:
        description: "Deployment environment"
        required: false
        default: ""

env:
  COMMIT_HASH: ${{ github.sha }}
  IMAGE_NAME: ${{ github.event.inputs.image_name || vars.IMAGE_NAME }}
  IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display GitHub Context Information
        run: |
          echo "Repository: ${{ github.repository }}, Actor: ${{ github.actor }}, Branch: ${{ github.ref_name }}"

      - name: Display Runner Information
        run: |
          echo "Running on OS: ${{ runner.os }} with ${{ runner.arch }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image to Docker Hub
        run: |
          echo "Building Docker image with name: ${{ env.IMAGE_NAME }} and tag: ${{ env.IMAGE_TAG }}"

          # Build and push with commit hash tag
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_HASH }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_HASH }}

          # Build and push with specified or default tag
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy-on-EC2-instance:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Display Deployment Context Information
        run: |
          echo "Deploying to EC2 host: ${{ secrets.EC2_HOST }} as user: ${{ secrets.EC2_USERNAME }}, Environment: ${{ github.event.inputs.deploy_env || 'production' }}"
          echo "Image Name: ${{ env.IMAGE_NAME }}"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"

      - name: Deploy on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

            # Stop and remove the existing container if it exists
            sudo docker stop NodeJs-Container || true
            sudo docker rm NodeJs-Container || true

            # Run the Docker container with a restart strategy
            sudo docker run -d --name NodeJs-Container --restart always -p 3001:3000 ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
